from collections.abc import Iterator
from typing import Any, Generic, TypeVar

_T = TypeVar("_T")

class _QuerySet(Generic[_T]):
    def filter(self, *args: Any, **kwargs: Any) -> _QuerySet[_T]: ...
    def order_by(self, *fields: str) -> _QuerySet[_T]: ...
    def all(self) -> _QuerySet[_T]: ...
    def get(self, **kwargs: Any) -> _T: ...
    def count(self) -> int: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __getitem__(self, index: int | slice) -> Any: ...

class _Manager(Generic[_T]):
    def all(self) -> _QuerySet[_T]: ...
    def filter(self, *args: Any, **kwargs: Any) -> _QuerySet[_T]: ...
    def get(self, **kwargs: Any) -> _T: ...
    def order_by(self, *fields: str) -> _QuerySet[_T]: ...

class Tag:
    pk: int
    name: str
    slug: str
    objects: _Manager[Tag]
